/*
   this is a placeholder include used to satisfy the include

   when used with Atmel START, this file will be overwritten
   with the user configuration generated by Atmel START
 */
 
 
#ifndef ATCA_START_IFACE_H
#define ATCA_START_IFACE_H

#endif
